#!/usr/bin/env python3
"""
Catalog generator for tools.openooda.org
Maintains exact parity for the 19 active sovereign repositories in the openOODA-tools organization.
"""

import json

released_tools = [
    {
        "id": "oosh",
        "name": "oosh",
        "category": "Shell & Terminal",
        "role": "SOVEREIGN SHELL",
        "version": "v1.0.1",
        "status": "released",
        "monogram": "SH",
        "accent": "#00e676",
        "description": "Sovereign interactive command plane engineered for direct systems control, ambient environment integration, and POSIX muscle memory.",
        "gem": True,
        "gemFact": "Ambient Intent · Zero Ambient Auth",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oosh/install.sh | bash",
        "overviewUrl": "oosh/",
        "repoUrl": "https://github.com/openOODA-tools/oosh",
        "tags": ["mcp-native", "zero-ambient-auth", "posix-muscle", "pure-openooda"],
        "capabilities": ["&TermCap", "&ProcCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-08-15"
    },
    {
        "id": "oogrep",
        "name": "oogrep",
        "category": "Search & Inspection",
        "role": "REGEX SEARCH",
        "version": "v0.3.2",
        "status": "released",
        "monogram": "GP",
        "accent": "#00e5ff",
        "description": "Capability-bounded recursive regex search. Fast directory traversal with column tracking, colored hunks, and an stdio MCP surface.",
        "gem": True,
        "gemFact": "Myers Regex Engine · stdio MCP Surface",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oogrep/install.sh | bash",
        "overviewUrl": "oogrep/",
        "repoUrl": "https://github.com/openOODA-tools/oogrep",
        "tags": ["mcp-native", "gitignore-aware", "posix-parity", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&McpCap"],
        "addedAt": "2026-08-20"
    },
    {
        "id": "oodiff",
        "name": "oodiff",
        "category": "Diff & Comparison",
        "role": "AST & TEXT DIFF",
        "version": "v0.3.1",
        "status": "released",
        "monogram": "DF",
        "accent": "#ffb300",
        "description": "Capability-bounded file and directory comparison. Byte-for-byte GNU normal and unified diff parity with negative-trust sandbox.",
        "gem": True,
        "gemFact": "GNU Byte-for-Byte Parity · LCS Myers Algorithm",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oodiff/install.sh | bash",
        "overviewUrl": "oodiff/",
        "repoUrl": "https://github.com/openOODA-tools/oodiff",
        "tags": ["gnu-parity", "lcs-myers", "apt-dnf", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&McpCap"],
        "addedAt": "2026-08-28"
    },
    {
        "id": "oofind",
        "name": "oofind",
        "category": "Files & Navigation",
        "role": "DIR TRAVERSAL",
        "version": "v0.2.1",
        "status": "released",
        "monogram": "FD",
        "accent": "#64ffda",
        "description": "Fast directory traversal with glob matching, type filtering, -print0 for xargs piping, and structured JSON output.",
        "gem": False,
        "gemFact": "Structured JSON Lines · Fast Glob Traversal",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oofind/install.sh | bash",
        "overviewUrl": "oofind/",
        "repoUrl": "https://github.com/openOODA-tools/oofind",
        "tags": ["mcp-native", "json-lines", "posix-parity", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&McpCap"],
        "addedAt": "2026-09-02"
    },
    {
        "id": "oojq",
        "name": "oojq",
        "category": "Data & Streaming",
        "role": "STREAMING JSON",
        "version": "v0.1.1",
        "status": "released",
        "monogram": "JQ",
        "accent": "#ff4081",
        "description": "High-fidelity jq replacement. Exact arithmetic boundaries, full filter parser, and capability-isolated JSON transformation.",
        "gem": True,
        "gemFact": "Exact Arithmetic Boundaries · Zero JSON Leakage",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oojq/install.sh | bash",
        "overviewUrl": "oojq/",
        "repoUrl": "https://github.com/openOODA-tools/oojq",
        "tags": ["exact-math", "zero-leakage", "pure-openooda", "mcp-native"],
        "capabilities": ["&FsReadCap", "&McpCap"],
        "addedAt": "2026-09-05"
    },
    {
        "id": "ootail",
        "name": "ootail",
        "category": "Data & Streaming",
        "role": "STREAM FOLLOWER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "TL",
        "accent": "#e040fb",
        "description": "Capability-bounded streaming file and event follower. Inotify change events, line and byte windowing, and native MCP stdio server.",
        "gem": True,
        "gemFact": "Inotify Event Follower · Stdio MCP Server",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ootail/install.sh | bash",
        "overviewUrl": "ootail/",
        "repoUrl": "https://github.com/openOODA-tools/ootail",
        "tags": ["inotify-watch", "truncate-safe", "pure-openooda", "mcp-native"],
        "capabilities": ["&FsReadCap", "&InotifyCap", "&McpCap"],
        "addedAt": "2026-09-10"
    },
    {
        "id": "oote",
        "name": "oote",
        "category": "Theme & Styling",
        "role": "THEME ENGINE",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "TE",
        "accent": "#7c4dff",
        "description": "Sovereign, unified theming and color styling engine. 25 circadian calendar themes, dynamic terminal palette synchronization, and MCP.",
        "gem": True,
        "gemFact": "25 Circadian Themes · Global Ecosystem Sync",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oote/install.sh | bash",
        "overviewUrl": "oote/",
        "repoUrl": "https://github.com/openOODA-tools/oote",
        "tags": ["theme-engine", "ansi-styling", "circadian-palettes", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&FsWriteCap", "&EnvCap", "&ProcessCap", "&McpCap"],
        "addedAt": "2026-09-15"
    },
    {
        "id": "oofetch",
        "name": "oofetch",
        "category": "System & Monitor",
        "role": "SYSTEM FETCH",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "FT",
        "accent": "#ffab40",
        "description": "Sovereign system fetch and environment showcase. Dynamic ASCII mascots, hardware & OS telemetry, zero ambient leakage, and stdio MCP.",
        "gem": True,
        "gemFact": "Dynamic ASCII Mascots · Hardware & OS Telemetry",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oofetch/install.sh | bash",
        "overviewUrl": "oofetch/",
        "repoUrl": "https://github.com/openOODA-tools/oofetch",
        "tags": ["ascii-art", "system-info", "zero-ambient-leak", "pure-openooda"],
        "capabilities": ["&SysInfoCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-09-18"
    },
    {
        "id": "oocat",
        "name": "oocat",
        "category": "Search & Inspection",
        "role": "VIEWER & PAGER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "CT",
        "accent": "#ffd740",
        "description": "Capability-bounded syntax-highlighting file viewer and pager. Multi-language lexing, range bounded paging, and stdio MCP inspection.",
        "gem": False,
        "gemFact": "Multi-Language Lexing · Range Bounded Paging",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oocat/install.sh | bash",
        "overviewUrl": "oocat/",
        "repoUrl": "https://github.com/openOODA-tools/oocat",
        "tags": ["syntax-highlighting", "pager-integration", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&TermCap", "&McpCap"],
        "addedAt": "2026-09-20"
    },
    {
        "id": "ootop",
        "name": "ootop",
        "category": "System & Monitor",
        "role": "PROCESS MONITOR",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "TP",
        "accent": "#69f0ae",
        "description": "Sovereign real-time system monitor and dashboard. Systemd slice telemetry, dynamic mascot moods, and streaming MCP telemetry.",
        "gem": False,
        "gemFact": "Systemd Slice Telemetry · Mascot Mood Dynamics",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ootop/install.sh | bash",
        "overviewUrl": "ootop/",
        "repoUrl": "https://github.com/openOODA-tools/ootop",
        "tags": ["systemd-slices", "emotional-mascot", "mcp-telemetry", "pure-openooda"],
        "capabilities": ["&ProcCap", "&SysInfoCap", "&TermCap", "&McpCap"],
        "addedAt": "2026-09-22"
    },
    {
        "id": "oofzf",
        "name": "oofzf",
        "category": "Search & Inspection",
        "role": "FUZZY FINDER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "FZ",
        "accent": "#18ffff",
        "description": "Sovereign interactive fuzzy finder and candidate ranker. Subsequence scoring with consecutive run bonuses, oote palettes, and stdio MCP.",
        "gem": True,
        "gemFact": "Subsequence Scoring · Consecutive Run Bonus",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oofzf/install.sh | bash",
        "overviewUrl": "oofzf/",
        "repoUrl": "https://github.com/openOODA-tools/oofzf",
        "tags": ["fuzzy-matching", "mcp-surface", "oote-palettes", "pure-openooda"],
        "capabilities": ["&TermCap", "&FsReadCap", "&McpCap"],
        "addedAt": "2026-09-25"
    },
    {
        "id": "ools",
        "name": "ools",
        "category": "Files & Navigation",
        "role": "DIR LISTER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "LS",
        "accent": "#b388ff",
        "description": "Sovereign directory lister and metadata classifier. Multi-column grid rendering, detailed long-format tables, oote palettes, and native MCP stdio server.",
        "gem": True,
        "gemFact": "Metadata Classification · Multi-Column Grid",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ools/install.sh | bash",
        "overviewUrl": "ools/",
        "repoUrl": "https://github.com/openOODA-tools/ools",
        "tags": ["metadata-class", "zero-ambient-auth", "mcp-surface", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-09-28"
    },
    {
        "id": "ootree",
        "name": "ootree",
        "category": "Files & Navigation",
        "role": "TREE VISUALIZER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "TR",
        "accent": "#64ffda",
        "description": "Sovereign directory hierarchy visualizer. Depth limiting, size sorting, oote color formatting, and MCP tree exploration.",
        "gem": False,
        "gemFact": "Depth-Bounded Traversal · Indent Matrix",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ootree/install.sh | bash",
        "overviewUrl": "ootree/",
        "repoUrl": "https://github.com/openOODA-tools/ootree",
        "tags": ["tree-traversal", "depth-limiting", "mcp-native", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-02"
    },
    {
        "id": "ooclock",
        "name": "ooclock",
        "category": "System & Monitor",
        "role": "MATRIX CLOCK",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "CK",
        "accent": "#00e5ff",
        "description": "Sovereign TUI digital matrix clock. Military time, custom seconds refresh cadences, color themes, and terminal resize responsiveness.",
        "gem": False,
        "gemFact": "Matrix Clock · Monotonic Time Sync",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ooclock/install.sh | bash",
        "overviewUrl": "ooclock/",
        "repoUrl": "https://github.com/openOODA-tools/ooclock",
        "tags": ["tui-clock", "time-sync", "oote-themes", "pure-openooda"],
        "capabilities": ["&TimeCap", "&TermCap", "&McpCap"],
        "addedAt": "2026-10-03"
    },
    {
        "id": "oosed",
        "name": "oosed",
        "category": "Data & Streaming",
        "role": "STREAM EDITOR",
        "version": "v0.1.0",
        "status": "released",
        "monogram": "SD",
        "accent": "#ff4081",
        "description": "Capability-bounded stream editor. Pattern matching, text substitution, in-place editing safety, and streaming transform pipeline.",
        "gem": False,
        "gemFact": "Stream Transformations · Substitution Engine",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oosed/install.sh | bash",
        "overviewUrl": "oosed/",
        "repoUrl": "https://github.com/openOODA-tools/oosed",
        "tags": ["stream-editor", "regex-substitution", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&FsWriteCap", "&McpCap"],
        "addedAt": "2026-10-04"
    },
    {
        "id": "ootar",
        "name": "ootar",
        "category": "Files & Navigation",
        "role": "ARCHIVE MANAGER",
        "version": "v0.1.0",
        "status": "released",
        "monogram": "AR",
        "accent": "#ff4081",
        "description": "Traversal-resistant archive utility. Prevents zip-slip and path traversal attacks by construction with capability-bounded extraction.",
        "gem": True,
        "gemFact": "Traversal-Resistant · Zero Zip-Slip",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ootar/install.sh | bash",
        "overviewUrl": "ootar/",
        "repoUrl": "https://github.com/openOODA-tools/ootar",
        "tags": ["tar-archive", "path-sanitization", "mcp-native", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&FsWriteCap", "&McpCap"],
        "addedAt": "2026-10-05"
    },
    {
        "id": "oops",
        "name": "oops",
        "category": "System & Monitor",
        "role": "PROCESS TABLE",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "PS",
        "accent": "#00b0ff",
        "description": "Sovereign process table and tree inspector. Visualizes user sessions, cgroups, systemd units, and capability privileges.",
        "gem": False,
        "gemFact": "Process Tree Hierarchy · Capability Audit",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oops/install.sh | bash",
        "overviewUrl": "oops/",
        "repoUrl": "https://github.com/openOODA-tools/oops",
        "tags": ["process-table", "process-tree", "systemd-cgroups", "pure-openooda"],
        "capabilities": ["&ProcCap", "&McpCap"],
        "addedAt": "2026-10-06"
    },
    {
        "id": "oocurl",
        "name": "oocurl",
        "category": "Network & Egress",
        "role": "HTTP CLIENT",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "CL",
        "accent": "#ffd740",
        "description": "Capability-bounded HTTP/HTTPS client. Zero ambient network egress, strict TLS validation, and streaming response output.",
        "gem": True,
        "gemFact": "Explicit NetCap · Zero Ambient Egress",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oocurl/install.sh | bash",
        "overviewUrl": "oocurl/",
        "repoUrl": "https://github.com/openOODA-tools/oocurl",
        "tags": ["http-client", "tls-validation", "zero-ambient-egress", "pure-openooda"],
        "capabilities": ["&NetCap", "&TlsCap", "&McpCap"],
        "addedAt": "2026-10-06"
    },
    {
        "id": "oowatch",
        "name": "oowatch",
        "category": "System & Monitor",
        "role": "INTERVAL WATCHER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "WT",
        "accent": "#00b0ff",
        "description": "Continuous command runner and watcher. Highlight deltas between consecutive executions with jitter-free timer scheduling.",
        "gem": False,
        "gemFact": "Periodic Execution · Delta Highlight",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oowatch/install.sh | bash",
        "overviewUrl": "oowatch/",
        "repoUrl": "https://github.com/openOODA-tools/oowatch",
        "tags": ["watch-runner", "delta-highlighting", "mcp-native", "pure-openooda"],
        "capabilities": ["&TimeCap", "&ProcCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "oomcp",
        "name": "oomcp",
        "category": "System & Monitor",
        "role": "COMPOSITE MCP GATEWAY",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "CP",
        "accent": "#bd93f9",
        "description": "Sovereign Model Context Protocol (MCP) composite gateway & tool router. Single unified stdio endpoint for all openOODA userland tools.",
        "gem": True,
        "gemFact": "Composite Gateway · Dynamic Discovery",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oomcp/install.sh | bash",
        "overviewUrl": "oomcp/",
        "repoUrl": "https://github.com/openOODA-tools/oomcp",
        "tags": ["mcp-gateway", "composite-router", "systemd-native", "pure-openooda"],
        "capabilities": ["&ProcessCap", "&FsReadCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "oo7z",
        "name": "oo7z",
        "category": "Files & Navigation",
        "role": "7Z HANDLER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "7Z",
        "accent": "#ff79c6",
        "description": "7-Zip multi-format container unpacker and lister with AES-256 encryption. Anti-zip-slip safe extraction and stdio MCP server.",
        "gem": True,
        "gemFact": "7-Zip Container · Traversal-Resistant",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oo7z/install.sh | bash",
        "overviewUrl": "oo7z/",
        "repoUrl": "https://github.com/openOODA-tools/oo7z",
        "tags": ["7z-container", "zipslip-safe", "posix-parity", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&FsWriteCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "ooalias",
        "name": "ooalias",
        "category": "Shell & Terminal",
        "role": "ALIAS RESOLVER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "AL",
        "accent": "#50fa7b",
        "description": "Cryptographically verifiable command macro and alias resolver with scope isolation, cycle detection, and stdio MCP server.",
        "gem": True,
        "gemFact": "Cycle-Safe Resolver · Scope Isolation",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ooalias/install.sh | bash",
        "overviewUrl": "ooalias/",
        "repoUrl": "https://github.com/openOODA-tools/ooalias",
        "tags": ["command-macro", "alias-resolver", "cycle-detection", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&FsWriteCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "ooansi",
        "name": "ooansi",
        "category": "Shell & Terminal",
        "role": "ANSI GENERATOR",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "AN",
        "accent": "#bd93f9",
        "description": "ANSI terminal sequence generator supporting 16-color, 256-color, TrueColor RGB, cursor manipulation, and stdio MCP server.",
        "gem": True,
        "gemFact": "TrueColor Generator · ANSI Stripper",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ooansi/install.sh | bash",
        "overviewUrl": "ooansi/",
        "repoUrl": "https://github.com/openOODA-tools/ooansi",
        "tags": ["ansi-sequences", "truecolor", "cursor-control", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "ooapparmor",
        "name": "ooapparmor",
        "category": "System & Monitor",
        "role": "SECURITY CONFINEMENT",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "AA",
        "accent": "#ff5555",
        "description": "Capability-bounded AppArmor security profile generator and confinement auditor with zero ambient authority enforcement and stdio MCP server.",
        "gem": True,
        "gemFact": "Profile Generator · Confinement Auditor",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ooapparmor/install.sh | bash",
        "overviewUrl": "ooapparmor/",
        "repoUrl": "https://github.com/openOODA-tools/ooapparmor",
        "tags": ["apparmor-profile", "least-privilege", "security-audit", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "ooarchive",
        "name": "ooarchive",
        "category": "Files & Navigation",
        "role": "ARCHIVE PACKER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "AP",
        "accent": "#ffb86c",
        "description": "Deterministic reproducible archive builder guaranteeing byte-for-byte outputs across TAR, CPIO, and AR formats with stdio MCP server.",
        "gem": True,
        "gemFact": "Reproducible Packing · Multi-Format Support",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ooarchive/install.sh | bash",
        "overviewUrl": "ooarchive/",
        "repoUrl": "https://github.com/openOODA-tools/ooarchive",
        "tags": ["reproducible-archive", "deterministic-tar", "anti-zipslip", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&FsWriteCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "ooarp",
        "name": "ooarp",
        "category": "Network & Egress",
        "role": "ARP CACHE TOOL",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "AP",
        "accent": "#50fa7b",
        "description": "Capability-bounded ARP cache and neighbor discovery auditor with IEEE 802 MAC validation and stdio MCP server.",
        "gem": True,
        "gemFact": "Neighbor Discovery · Spoofing Auditor",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ooarp/install.sh | bash",
        "overviewUrl": "ooarp/",
        "repoUrl": "https://github.com/openOODA-tools/ooarp",
        "tags": ["arp-cache", "neighbor-discovery", "mac-audit", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&NetCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "ooastdiff",
        "name": "ooastdiff",
        "category": "Diff & Comparison",
        "role": "AST SYNTAX DIFFER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "AD",
        "accent": "#f1fa8c",
        "description": "Language-agnostic AST syntax-aware diffing tool with token LCS alignment, comment/whitespace insensitivity, and stdio MCP server.",
        "gem": True,
        "gemFact": "Syntax LCS Diff · Comment/Spacing Agnostic",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ooastdiff/install.sh | bash",
        "overviewUrl": "ooastdiff/",
        "repoUrl": "https://github.com/openOODA-tools/ooastdiff",
        "tags": ["ast-diff", "syntax-differ", "token-lcs", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "ooat",
        "name": "ooat",
        "category": "System & Monitor",
        "role": "ONESHOT TIMER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "AT",
        "accent": "#50fa7b",
        "description": "Single-run scheduled command coordinator backed by transient systemd timer units with stdio MCP server.",
        "gem": True,
        "gemFact": "Systemd Transient Timer · Zero Ambient Cron",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ooat/install.sh | bash",
        "overviewUrl": "ooat/",
        "repoUrl": "https://github.com/openOODA-tools/ooat",
        "tags": ["oneshot-timer", "systemd-native", "scheduled-task", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "ooattest",
        "name": "ooattest",
        "category": "System & Monitor",
        "role": "TPM ATTESTATION",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "AT",
        "accent": "#ff5555",
        "description": "Attests system state and measured boot hashes using TPM2 hardware security chips with stdio MCP server.",
        "gem": True,
        "gemFact": "TPM2 Attestation · Measured Boot Registers",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ooattest/install.sh | bash",
        "overviewUrl": "ooattest/",
        "repoUrl": "https://github.com/openOODA-tools/ooattest",
        "tags": ["tpm2-attestation", "pcr-audit", "measured-boot", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "ooaudit",
        "name": "ooaudit",
        "category": "Security & Audit",
        "role": "ACTION LEDGER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "AU",
        "accent": "#ffb86c",
        "description": "Immutable audit recorder logging system calls, IO streams, and agent decisions with cryptographic hash chains and stdio MCP server.",
        "gem": True,
        "gemFact": "Cryptographic Hash Chains · Tamper Detection",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ooaudit/install.sh | bash",
        "overviewUrl": "ooaudit/",
        "repoUrl": "https://github.com/openOODA-tools/ooaudit",
        "tags": ["action-ledger", "hash-chain", "audit-log", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&FsWriteCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "ooawk",
        "name": "ooawk",
        "category": "Text & Filter",
        "role": "RECORD PROCESSOR",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "AW",
        "accent": "#50fa7b",
        "description": "Data-driven pattern scanning and text processing language with exact arithmetic, field projection, and stdio MCP server.",
        "gem": True,
        "gemFact": "Exact Arithmetic · Field Projection",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/ooawk/install.sh | bash",
        "overviewUrl": "ooawk/",
        "repoUrl": "https://github.com/openOODA-tools/ooawk",
        "tags": ["record-processor", "pattern-scanning", "exact-arithmetic", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "oob3sum",
        "name": "oob3sum",
        "category": "Security & Audit",
        "role": "BLAKE3 HASHER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "B3",
        "accent": "#00e5ff",
        "description": "Blistering BLAKE3 tree hasher achieving multi-gigabyte per second throughput with stdio MCP server.",
        "gem": True,
        "gemFact": "BLAKE3 Tree Hasher · 1024-Byte Chunks",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oob3sum/install.sh | bash",
        "overviewUrl": "oob3sum/",
        "repoUrl": "https://github.com/openOODA-tools/oob3sum",
        "tags": ["blake3", "cryptographic-hasher", "tree-hashing", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "oobackup",
        "name": "oobackup",
        "category": "Files & Navigation",
        "role": "SNAPSHOT COORDINATOR",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "BK",
        "accent": "#00e5ff",
        "description": "Point-in-time snapshot coordinator creating deduplicated, content-addressed file trees with stdio MCP server.",
        "gem": True,
        "gemFact": "Merkle Snapshots · 3-Way Differential Engine",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oobackup/install.sh | bash",
        "overviewUrl": "oobackup/",
        "repoUrl": "https://github.com/openOODA-tools/oobackup",
        "tags": ["backup", "snapshot-engine", "merkle-tree", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&FsWriteCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "oobanner",
        "name": "oobanner",
        "category": "Theme & Styling",
        "role": "FIGLET ENGINE",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "BN",
        "accent": "#00e5ff",
        "description": "Renders stylized ASCII art banners, typography, and logos in the terminal with stdio MCP server.",
        "gem": True,
        "gemFact": "FIGLET Typography · Multi-Line ANSI Marquee Frames",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oobanner/install.sh | bash",
        "overviewUrl": "oobanner/",
        "repoUrl": "https://github.com/openOODA-tools/oobanner",
        "tags": ["figlet", "banner", "ascii-art", "typography", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "oobar",
        "name": "oobar",
        "category": "Theme & Styling",
        "role": "PROGRESS METER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "BR",
        "accent": "#00e5ff",
        "description": "Renders smooth terminal progress bars with ETA, throughput, and percent gauges with stdio MCP server.",
        "gem": True,
        "gemFact": "Progress Meter · Multi-Style Tracks & ETA Engine",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oobar/install.sh | bash",
        "overviewUrl": "oobar/",
        "repoUrl": "https://github.com/openOODA-tools/oobar",
        "tags": ["progress-bar", "meter", "gauges", "eta", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "oobase32",
        "name": "oobase32",
        "category": "Data & Serialization",
        "role": "BASE32 CODEC",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "32",
        "accent": "#00ffcc",
        "description": "Sovereign Base32 encoder and decoder with Crockford, Extended Hex, and RFC 4648 alphabet options.",
        "gem": True,
        "gemFact": "Base32 Codec · Multi-Alphabet & Visual Collision Normalizer",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oobase32/install.sh | bash",
        "overviewUrl": "oobase32/",
        "repoUrl": "https://github.com/openOODA-tools/oobase32",
        "tags": ["base32", "codec", "rfc4648", "crockford", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "oobase58",
        "name": "oobase58",
        "category": "Data & Serialization",
        "role": "BASE58 CODEC",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "58",
        "accent": "#ff9100",
        "description": "Cryptographic Base58 encoder and decoder omitting ambiguous alphanumeric glyphs with stdio MCP server.",
        "gem": True,
        "gemFact": "Base58 Codec · Multi-Alphabet & Arbitrary-Precision Engine",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oobase58/install.sh | bash",
        "overviewUrl": "oobase58/",
        "repoUrl": "https://github.com/openOODA-tools/oobase58",
        "tags": ["base58", "codec", "bitcoin", "ripple", "flickr", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "oobase64",
        "name": "oobase64",
        "category": "Data & Serialization",
        "role": "BASE64 CODEC",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "64",
        "accent": "#76ff03",
        "description": "SIMD-accelerated RFC 4648 Base64 data encoder and decoder with URL-safe variants and stdio MCP server.",
        "gem": True,
        "gemFact": "Base64 Codec · Standard & URL-Safe Dual-Variant Engine",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oobase64/install.sh | bash",
        "overviewUrl": "oobase64/",
        "repoUrl": "https://github.com/openOODA-tools/oobase64",
        "tags": ["base64", "codec", "rfc4648", "url-safe", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    },
    {
        "id": "oobasename",
        "name": "oobasename",
        "category": "Filesystem & Navigation",
        "role": "PATH STRIPPER",
        "version": "v0.2.0",
        "status": "released",
        "monogram": "BN",
        "accent": "#00b0ff",
        "description": "Strips directory prefixes and optional file extensions from path strings with stdio MCP server.",
        "gem": True,
        "gemFact": "Path Stripper · POSIX Basename & Batch Collection Engine",
        "installCommand": "curl -fsSL https://openooda-tools.github.io/oobasename/install.sh | bash",
        "overviewUrl": "oobasename/",
        "repoUrl": "https://github.com/openOODA-tools/oobasename",
        "tags": ["basename", "path", "filename", "posix", "pure-openooda"],
        "capabilities": ["&FsReadCap", "&ProcessCap", "&EnvCap", "&McpCap"],
        "addedAt": "2026-10-07"
    }
]

# Total items count strictly based on actual repositories in @openOODA-tools
all_tools = list(released_tools)

print(f"Total tools generated: {len(all_tools)}")
assert len(all_tools) == 39, f"Expected 39 tools, got {len(all_tools)}"
assert len(set(t["id"] for t in all_tools)) == 39, "Duplicate tool ID detected!"

# Write data/tools.json
with open("data/tools.json", "w") as f:
    json.dump(all_tools, f, indent=2)

category_set = sorted(list(set(t["category"] for t in all_tools)))
categories = ["All Categories"] + category_set

# Write assets/js/tools-data.js
js_content = f"""// openOODA Tools Catalog Data (Actual Repositories)
// Generated automatically with 100% parity for all 19 active repositories

export const TOOLS_DATA = {json.dumps(all_tools, indent=2)};

export const CATEGORIES = {json.dumps(categories, indent=2)};

export const STATUS_FILTERS = [
  {{ id: "all", label: "All Repos", count: {len(all_tools)} }},
  {{ id: "released", label: "Released", count: {len(all_tools)} }}
];
"""

with open("assets/js/tools-data.js", "w") as f:
    f.write(js_content)

print("Successfully written data/tools.json and assets/js/tools-data.js")
